* Introduction
A DEPRECATED unofficial, experimental SDL2 backend for McCLIM.

- Update: 2022-09-01 Daniel Kochmański has created an official sdl2 backend in
  the McCLIM repository. It's in the [[https://github.com/McCLIM/McCLIM/tree/backend-sdl2][backend-sdl2 branch]]. This project is now
  deprecated and I'm only using it for personal experiments.

- 2022-08-19 A note from Joel Boehland (jolby).

This is an attempt to build on the work of Elias Mårtenson in the sdl-test
branch of the McCLIM repository and the documentation for creating backend by
the primary maintainer of McCLIM, Daniel Kochmański (jackdaniel). I am also
doing this for my own curiosity and education to get a deeper understanding of CLIM
and how it is implemented.

* Resources
Daniel Kochmański has published a number of tutorials and guides explaining the
different parts and roles of the components in a CLIM backend implementation. In
addition, he has recently reshaped the codebase to make these roles more clear
and easier for a new backend to be implemented.

- [[http://turtleware.eu/posts/McCLIM-backends---Part-I-Medium-Output-Protocol.html][McCLIM backends - Part I: Medium Output Protocol]]
- [[http://turtleware.eu/posts/McCLIM-backends---Part-2-Stream-Output-Protocol.html][McCLIM backends - Part 2: Stream Output Protocol]]
- [[http://turtleware.eu/posts/A-tale-of-two-abstractions.html][A tale of two abstractions]] A good overall document mapping the different parts
  of McCLIM to modern graphical windowing systems.
- [[https://mcclim.common-lisp.dev/posts/Sheets-as-ideal-forms.html][Sheets as Ideal Forms]] Great document explaining the linkage between physical
  devices and grafts, mediums and ports.
- [[https://github.com/McCLIM/McCLIM/blob/backend-sdl2/Backends/SDL2/README.org][SDL backend implementor's guide.]] by Daniel Kochmański. Now in McCLIM repo.
- [[https://irclog.tymoon.eu/libera/%23clim?from=2022-01-01T06%3A28%3A12&to=2022-08-30T18%3A28%3A12&search=sdl&by][Search #clim irc channel for sdl]]
